package com.example.routeguard.enums;

public enum DecisionReasonCode {
    ALL_EVIDENCE_VERIFIED,

    GPS_EVIDENCE_MISSING,
    GPS_DISTANCE_EXCEEDED,

    OTP_EVIDENCE_MISSING,
    OTP_INVALID,

    PHOTO_EVIDENCE_MISSING,
    PHOTO_REUSED,

    CONTACT_ATTEMPT_MISSING,
    FAILURE_REASON_MISSING,

    EVENT_TIMESTAMP_STALE,
    EVIDENCE_CONFLICT,
    INSUFFICIENT_EVIDENCE
}