spring.application.name=routeguard
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5438/routeguard_db
spring.datasource.username=routeguard_user
spring.datasource.password=routeguard_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

security.jwt.secret=${JWT_SECRET:routeguard-local-jwt-secret-change-this-1234567890}
security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

routeguard.evaluation.maximum-gps-distance-metres=200